---
version: "3.9"
services:
  mgmt-node:
    build: ./build/execution/
    command: receptor -c /etc/receptor/receptor.conf
    volumes:
      - ./configs/mgmt-receptor.conf:/etc/receptor/receptor.conf
    networks:
      - receptor-network

  hop-node:
    build: ./build/hop/
    command: receptor -c /etc/receptor/receptor.conf
    volumes:
      - ./configs/hop-receptor.conf:/etc/receptor/receptor.conf
    networks:
      - iso-network
      - receptor-network

  iso-node:
    build: ./build/execution/
    command: receptor -c /etc/receptor/receptor.conf
    volumes:
      - ./configs/iso-receptor.conf:/etc/receptor/receptor.conf
    networks:
      - iso-network

networks:
  receptor-network:
    driver: bridge

  iso-network:
    driver: bridge
